### ISSUE TITLE
As EGIT_COMMIT is set, the packages are not really "live"

### ISSUE THREAD

**Issue by filmor** [fsvm88/cosmic-overlay#10]
It's currently not really possible to update Cosmic packages, as `EGIT_COMMIT` changes are not represented in the version. Live ebuilds (9999 version) are expected to not be tied to a particular commit. Since this is not the case, `smart-live-rebuild` will not detect changes. `emerge @live-rebuild` is blunt in that it just unconditionally recompiles everything.

I would suggest to either

- switch to date-based versioning (`20240909`)
- bump the ebuild revision on each update (`9999-r3`)

**Comment by fsvm88** [comment]
Hi, I was considering this myself lately, I agree.

Would the following changes make sense to you?
- we create a set of versioned ebuilds (based on `epoch-1.0.0-alpha.1` tag, just noticed in the cosmic repos)
- 9999 ebuilds point to master branch

I would avoid adding date-based ebuilds, because I would need to regenerate the list of crates in each ebuild at a different date, and anyway COSMIC is not shipping in date-based increments.

**Comment by filmor** [comment]
That's all fine. The date-based approach was not meant to imply that there are date-based releases. It was just meant to provide an increasing version number such that newer versions can be installed sooner. This is the approach that the Fedora COPR uses (`1.0.0-<date>git<commit-hash>`).

The only problem with using the tags on the epoch repo is that there doesn't seem to be a lot of tagging activity right now. Looks more like they are running the alpha in a rolling release fashion.

**Comment by fsvm88** [comment]
I've published `1.0.0_alpha1` ebuilds, and `9999` ebuilds now point to `master` branch.

I've tried to compile both sets and they seem to be working fine. Note that I haven't rechecked yet for possible packaging changes (installed files).

I'll leave this open for feedback, let me know if you have issues.
