### ISSUE TITLE
cosmic-greeter GID UID

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#2]
I've decided to choose 600 as the lucky number for this.

Following the rules here https://projects.gentoo.org/qa/policy-guide/user-group.html and taking into account the assignment table here https://wiki.gentoo.org/wiki/UID_GID_Assignment_Table

**Comment by joostruis** [comment]
Did you get the cosmic-greeter to work yourself by the way?

**Comment by fsvm88** [comment]
I believe 600 should be ok, I hope it doesn't potentially clash with anything else from other overlays. It's really only used to run the daemon and provide access to `/var/lib/cosmic-greeter` AFAIK, so it should be trivial to change. I can create new versions of the ebuilds.

Regarding the second question: do you mean if I can run the greeter? Last time I tried, with the ebuilds I had, it worked out of the box. I just stopped the `greetd` systemd unit, and started `cosmic-greeter` instead.

**Comment by fsvm88** [comment]
I see.

I retested and can confirm: `cosmic-greeter` won't start because of https://github.com/pop-os/cosmic-greeter/blob/cc744b0b9a6065a97808744bf63433c439e4186c/debian/cosmic-greeter.service#L21 being commented -> without these lines, the unit appears static, and even if you enable it at boot it won't start properly.

Uncommenting these lines fixes it. I probably did it manually last time I tested.

Will submit changes (probably later today) to fix this.

I will also release new `-1` ebuilds for user/group with the proposed UID/GID.

**Comment by fsvm88** [comment]
`acct-{group,user}/cosmic-greeter-1` out with UID+GID 600.

Also fixed systemd unit for cosmic-greeter (and now also cloning LFS objects for cosmic-greeter).

I'll look at your bump PR soon, I suspect for cosmic-notifications the Cargo.toml structure changed a bit, should be quick to debug.
