### ISSUE TITLE
Version information missing in about

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#34]
![image](https://github.com/user-attachments/assets/f23d1b85-97e2-4293-9cb6-f46365c2bd9e)

Same on text-editor and other applications. Happens since alpha4

**Comment by fsvm88** [comment]
AH, damn... This must be due to https://github.com/fsvm88/cosmic-overlay/blob/main/eclass/cosmic-de.eclass#L163

I had to add it because otherwise e.g.: cosmic-edit wouldn't compile:
- some deps are imported via git
- when the dep folder is vendored in the work folder, during emerge, `.git` folder gets deleted
- build scripts based on `vergen` complain when compiling the dep, because the dep folder does not look like a git repo

But now this seems to have broken the main program.

Let me try and override this info from the main program repo in $WORKDIR. For deps we really don't care anyways, these scripts are there only to trigger rebuilds if something changes (which when emerging, it shouldn't, unless one tampers with $WORKDIR).

**Comment by fsvm88** [comment]
`f7a40567291d433240d66b4470ac6fee850ad3a9` is now on `main`, please test =)

I gave it a quick round of testing and it seems to be working.

**Comment by joostruis** [comment]
Indeed. Seems solved!

![image](https://github.com/user-attachments/assets/cd2c6442-884e-4da0-a8ba-d16e3021a9a3)
